version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5433:5432"

  web:
    build: .
    image: spam-web
    working_dir: /code
    command: ["./wait-for-it.sh", "db/5432", "/code/runserver.sh"]
    user: root
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db