version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
  web:
    build: .
    command: sh runserver.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
